version: "3.8"

services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
  actual_server:
    image: ghcr.io/actualbudget/actual-server:latest-alpine
    ports:
      - "5006:5006"
    volumes:
      - actual_data:/data
    environment:
      - NODE_ENV=production

volumes:
  actual_data:
