version: "3.8"

services:
  actualbudget:
    image: ghcr.io/actualbudget/actual-server:latest-alpine
    ports:
      - "5006:5006"
    volumes:
      - actual_data:/data
    environment:
      - NODE_ENV=production

volumes:
  actual_data:
